version = 0.1

[[task]]
name = 'package'
run = 'deno run --allow-env --allow-net --allow-read --allow-run --allow-write scripts/build_npm.js'

[[task]]
name = 'publish'
deps = ['package']
run = 'cd _npm && npm publish --access public'

[[task]]
name = 'test'
run = 'deno test --allow-net --allow-read --import-map import_map.json test.js'
